name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build and Debug
        run: |
          flutter pub get
          # استفاده از فلگ‌های اختصاصی برای رفع ارورهای بیلد
          flutter build apk --release --no-tree-shake-icons
          
          # این دستور باعث میشه فایل‌های تولید شده رو در لاگ ببینیم
          echo "Listing build directory:"
          find build -name "*.apk"
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/*.apk
